#############################################################################
# Makefile for building: iris
# Generated by qmake (2.01a) (Qt 4.8.7) on: Fri Apr 24 11:58:49 2020
# Project:  iris.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile iris.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/default -I. -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include -I. -Iinclude -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib64 -lQtGui -L/usr/lib64 -L/usr/X11R6/lib -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/main.cpp \
		src/mainwindow.cpp \
		src/codes/iriscode.cpp \
		src/filters/coswavelet.cpp \
		src/filters/dilationfilter.cpp \
		src/filters/erosionfilter.cpp \
		src/filters/filter.cpp \
		src/filters/gaussian.cpp \
		src/filters/gaussianfilter.cpp \
		src/filters/imagefilter.cpp \
		src/filters/median.cpp \
		src/filters/sinusoidal.cpp \
		src/filters/sinwavelet.cpp \
		src/filters/sobelfilter.cpp \
		src/filters/sobelfilterx.cpp \
		src/filters/sobelfiltery.cpp \
		src/processing/eimage.cpp \
		src/processing/gabortoimage.cpp \
		src/processing/gabortopixel.cpp \
		src/processing/processiris.cpp \
		src/processing/histogram.cpp \
		src/ui/irisview.cpp \
		src/ui/mainview.cpp \
		src/ui/preferences.cpp \
		src/ui/uicircle.cpp \
		src/ui/uielement.cpp \
		src/ui/uiparabola.cpp \
		src/utils/database.cpp \
		src/utils/eutils.cpp \
		src/ui/matchdialog.cpp \
		src/ui/uibarchart.cpp moc_irisview.cpp \
		moc_mainview.cpp \
		moc_mainwindow.cpp \
		moc_processiris.cpp \
		moc_uicircle.cpp \
		moc_uielement.cpp \
		moc_uiparabola.cpp \
		moc_matchdialog.cpp \
		qrc_imgs.cpp
OBJECTS       = main.o \
		mainwindow.o \
		iriscode.o \
		coswavelet.o \
		dilationfilter.o \
		erosionfilter.o \
		filter.o \
		gaussian.o \
		gaussianfilter.o \
		imagefilter.o \
		median.o \
		sinusoidal.o \
		sinwavelet.o \
		sobelfilter.o \
		sobelfilterx.o \
		sobelfiltery.o \
		eimage.o \
		gabortoimage.o \
		gabortopixel.o \
		processiris.o \
		histogram.o \
		irisview.o \
		mainview.o \
		preferences.o \
		uicircle.o \
		uielement.o \
		uiparabola.o \
		database.o \
		eutils.o \
		matchdialog.o \
		uibarchart.o \
		moc_irisview.o \
		moc_mainview.o \
		moc_mainwindow.o \
		moc_processiris.o \
		moc_uicircle.o \
		moc_uielement.o \
		moc_uiparabola.o \
		moc_matchdialog.o \
		qrc_imgs.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		iris.pro
QMAKE_TARGET  = iris
DESTDIR       = 
TARGET        = iris

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: iris.pro  /usr/share/qt4/mkspecs/default/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib64/libQtGui.prl \
		/usr/lib64/libQtCore.prl
	$(QMAKE) -unix -o Makefile iris.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib64/libQtGui.prl:
/usr/lib64/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile iris.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/iris1.0.0 || $(MKDIR) .tmp/iris1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/iris1.0.0/ && $(COPY_FILE) --parents include/coswavelet.h include/database.h include/dilationfilter.h include/eimage.h include/erosionfilter.h include/eutils.h include/filter.h include/gabortoimage.h include/gabortopixel.h include/gaussian.h include/gaussianfilter.h include/imagefilter.h include/iriscode.h include/irisview.h include/mainview.h include/mainwindow.h include/median.h include/preferences.h include/processiris.h include/sinusoidal.h include/sinwavelet.h include/sobelfilter.h include/sobelfilterx.h include/sobelfiltery.h include/uicircle.h include/uielement.h include/uiparabola.h include/matchdialog.h include/uibarchart.h include/histogram.h .tmp/iris1.0.0/ && $(COPY_FILE) --parents imgs.qrc .tmp/iris1.0.0/ && $(COPY_FILE) --parents src/main.cpp src/mainwindow.cpp src/codes/iriscode.cpp src/filters/coswavelet.cpp src/filters/dilationfilter.cpp src/filters/erosionfilter.cpp src/filters/filter.cpp src/filters/gaussian.cpp src/filters/gaussianfilter.cpp src/filters/imagefilter.cpp src/filters/median.cpp src/filters/sinusoidal.cpp src/filters/sinwavelet.cpp src/filters/sobelfilter.cpp src/filters/sobelfilterx.cpp src/filters/sobelfiltery.cpp src/processing/eimage.cpp src/processing/gabortoimage.cpp src/processing/gabortopixel.cpp src/processing/processiris.cpp src/processing/histogram.cpp src/ui/irisview.cpp src/ui/mainview.cpp src/ui/preferences.cpp src/ui/uicircle.cpp src/ui/uielement.cpp src/ui/uiparabola.cpp src/utils/database.cpp src/utils/eutils.cpp src/ui/matchdialog.cpp src/ui/uibarchart.cpp .tmp/iris1.0.0/ && (cd `dirname .tmp/iris1.0.0` && $(TAR) iris1.0.0.tar iris1.0.0 && $(COMPRESS) iris1.0.0.tar) && $(MOVE) `dirname .tmp/iris1.0.0`/iris1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/iris1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_irisview.cpp moc_mainview.cpp moc_mainwindow.cpp moc_processiris.cpp moc_uicircle.cpp moc_uielement.cpp moc_uiparabola.cpp moc_matchdialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_irisview.cpp moc_mainview.cpp moc_mainwindow.cpp moc_processiris.cpp moc_uicircle.cpp moc_uielement.cpp moc_uiparabola.cpp moc_matchdialog.cpp
moc_irisview.cpp: include/irisview.h
	/usr/bin/moc $(DEFINES) $(INCPATH) include/irisview.h -o moc_irisview.cpp

moc_mainview.cpp: include/mainview.h
	/usr/bin/moc $(DEFINES) $(INCPATH) include/mainview.h -o moc_mainview.cpp

moc_mainwindow.cpp: include/mainwindow.h
	/usr/bin/moc $(DEFINES) $(INCPATH) include/mainwindow.h -o moc_mainwindow.cpp

moc_processiris.cpp: include/filter.h \
		include/uiparabola.h \
		include/uielement.h \
		include/uicircle.h \
		include/median.h \
		include/imagefilter.h \
		include/sinwavelet.h \
		include/sinusoidal.h \
		include/coswavelet.h \
		include/gabortopixel.h \
		include/gaussian.h \
		include/eimage.h \
		include/processiris.h
	/usr/bin/moc $(DEFINES) $(INCPATH) include/processiris.h -o moc_processiris.cpp

moc_uicircle.cpp: include/uielement.h \
		include/uicircle.h
	/usr/bin/moc $(DEFINES) $(INCPATH) include/uicircle.h -o moc_uicircle.cpp

moc_uielement.cpp: include/uielement.h
	/usr/bin/moc $(DEFINES) $(INCPATH) include/uielement.h -o moc_uielement.cpp

moc_uiparabola.cpp: include/uielement.h \
		include/uicircle.h \
		include/uiparabola.h
	/usr/bin/moc $(DEFINES) $(INCPATH) include/uiparabola.h -o moc_uiparabola.cpp

moc_matchdialog.cpp: include/matchdialog.h
	/usr/bin/moc $(DEFINES) $(INCPATH) include/matchdialog.h -o moc_matchdialog.cpp

compiler_rcc_make_all: qrc_imgs.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_imgs.cpp
qrc_imgs.cpp: imgs.qrc \
		images/ego.png
	/usr/bin/rcc -name imgs imgs.qrc -o qrc_imgs.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

main.o: src/main.cpp include/mainwindow.h \
		include/eimage.h \
		include/imagefilter.h \
		include/filter.h \
		include/median.h \
		include/gaussianfilter.h \
		include/sobelfilterx.h \
		include/sobelfilter.h \
		include/sobelfiltery.h \
		include/erosionfilter.h \
		include/dilationfilter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

mainwindow.o: src/mainwindow.cpp include/mainwindow.h \
		include/irisview.h \
		include/mainview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o src/mainwindow.cpp

iriscode.o: src/codes/iriscode.cpp include/iriscode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o iriscode.o src/codes/iriscode.cpp

coswavelet.o: src/filters/coswavelet.cpp include/coswavelet.h \
		include/sinusoidal.h \
		include/filter.h \
		include/eutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o coswavelet.o src/filters/coswavelet.cpp

dilationfilter.o: src/filters/dilationfilter.cpp include/dilationfilter.h \
		include/imagefilter.h \
		include/filter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dilationfilter.o src/filters/dilationfilter.cpp

erosionfilter.o: src/filters/erosionfilter.cpp include/erosionfilter.h \
		include/imagefilter.h \
		include/filter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o erosionfilter.o src/filters/erosionfilter.cpp

filter.o: src/filters/filter.cpp include/filter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o filter.o src/filters/filter.cpp

gaussian.o: src/filters/gaussian.cpp include/gaussian.h \
		include/filter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gaussian.o src/filters/gaussian.cpp

gaussianfilter.o: src/filters/gaussianfilter.cpp include/gaussianfilter.h \
		include/imagefilter.h \
		include/filter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gaussianfilter.o src/filters/gaussianfilter.cpp

imagefilter.o: src/filters/imagefilter.cpp include/imagefilter.h \
		include/filter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o imagefilter.o src/filters/imagefilter.cpp

median.o: src/filters/median.cpp include/median.h \
		include/imagefilter.h \
		include/filter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o median.o src/filters/median.cpp

sinusoidal.o: src/filters/sinusoidal.cpp include/sinusoidal.h \
		include/filter.h \
		include/gaussian.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sinusoidal.o src/filters/sinusoidal.cpp

sinwavelet.o: src/filters/sinwavelet.cpp include/sinwavelet.h \
		include/sinusoidal.h \
		include/filter.h \
		include/eutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sinwavelet.o src/filters/sinwavelet.cpp

sobelfilter.o: src/filters/sobelfilter.cpp include/sobelfilter.h \
		include/imagefilter.h \
		include/filter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sobelfilter.o src/filters/sobelfilter.cpp

sobelfilterx.o: src/filters/sobelfilterx.cpp include/sobelfilterx.h \
		include/sobelfilter.h \
		include/imagefilter.h \
		include/filter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sobelfilterx.o src/filters/sobelfilterx.cpp

sobelfiltery.o: src/filters/sobelfiltery.cpp include/sobelfiltery.h \
		include/sobelfilter.h \
		include/imagefilter.h \
		include/filter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sobelfiltery.o src/filters/sobelfiltery.cpp

eimage.o: src/processing/eimage.cpp include/eimage.h \
		include/imagefilter.h \
		include/filter.h \
		include/median.h \
		include/histogram.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o eimage.o src/processing/eimage.cpp

gabortoimage.o: src/processing/gabortoimage.cpp include/gabortoimage.h \
		include/gabortopixel.h \
		include/filter.h \
		include/sinusoidal.h \
		include/sinwavelet.h \
		include/coswavelet.h \
		include/gaussian.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gabortoimage.o src/processing/gabortoimage.cpp

gabortopixel.o: src/processing/gabortopixel.cpp include/gabortopixel.h \
		include/filter.h \
		include/sinusoidal.h \
		include/sinwavelet.h \
		include/coswavelet.h \
		include/gaussian.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gabortopixel.o src/processing/gabortopixel.cpp

processiris.o: src/processing/processiris.cpp include/processiris.h \
		include/filter.h \
		include/uiparabola.h \
		include/uielement.h \
		include/uicircle.h \
		include/median.h \
		include/imagefilter.h \
		include/sinwavelet.h \
		include/sinusoidal.h \
		include/coswavelet.h \
		include/gabortopixel.h \
		include/gaussian.h \
		include/eimage.h \
		include/gaussianfilter.h \
		include/sobelfilterx.h \
		include/sobelfilter.h \
		include/sobelfiltery.h \
		include/erosionfilter.h \
		include/dilationfilter.h \
		include/gabortoimage.h \
		include/iriscode.h \
		include/eutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o processiris.o src/processing/processiris.cpp

histogram.o: src/processing/histogram.cpp include/histogram.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o histogram.o src/processing/histogram.cpp

irisview.o: src/ui/irisview.cpp include/irisview.h \
		include/uicircle.h \
		include/uielement.h \
		include/processiris.h \
		include/filter.h \
		include/uiparabola.h \
		include/median.h \
		include/imagefilter.h \
		include/sinwavelet.h \
		include/sinusoidal.h \
		include/coswavelet.h \
		include/gabortopixel.h \
		include/gaussian.h \
		include/eimage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o irisview.o src/ui/irisview.cpp

mainview.o: src/ui/mainview.cpp include/irisview.h \
		include/processiris.h \
		include/filter.h \
		include/uiparabola.h \
		include/uielement.h \
		include/uicircle.h \
		include/median.h \
		include/imagefilter.h \
		include/sinwavelet.h \
		include/sinusoidal.h \
		include/coswavelet.h \
		include/gabortopixel.h \
		include/gaussian.h \
		include/eimage.h \
		include/mainview.h \
		include/iriscode.h \
		include/database.h \
		include/matchdialog.h \
		include/uibarchart.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainview.o src/ui/mainview.cpp

preferences.o: src/ui/preferences.cpp include/preferences.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o preferences.o src/ui/preferences.cpp

uicircle.o: src/ui/uicircle.cpp include/uicircle.h \
		include/uielement.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o uicircle.o src/ui/uicircle.cpp

uielement.o: src/ui/uielement.cpp include/uielement.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o uielement.o src/ui/uielement.cpp

uiparabola.o: src/ui/uiparabola.cpp include/uiparabola.h \
		include/uielement.h \
		include/uicircle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o uiparabola.o src/ui/uiparabola.cpp

database.o: src/utils/database.cpp include/database.h \
		include/iriscode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o database.o src/utils/database.cpp

eutils.o: src/utils/eutils.cpp include/eutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o eutils.o src/utils/eutils.cpp

matchdialog.o: src/ui/matchdialog.cpp include/matchdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o matchdialog.o src/ui/matchdialog.cpp

uibarchart.o: src/ui/uibarchart.cpp include/uibarchart.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o uibarchart.o src/ui/uibarchart.cpp

moc_irisview.o: moc_irisview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_irisview.o moc_irisview.cpp

moc_mainview.o: moc_mainview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainview.o moc_mainview.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_processiris.o: moc_processiris.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_processiris.o moc_processiris.cpp

moc_uicircle.o: moc_uicircle.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_uicircle.o moc_uicircle.cpp

moc_uielement.o: moc_uielement.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_uielement.o moc_uielement.cpp

moc_uiparabola.o: moc_uiparabola.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_uiparabola.o moc_uiparabola.cpp

moc_matchdialog.o: moc_matchdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_matchdialog.o moc_matchdialog.cpp

qrc_imgs.o: qrc_imgs.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_imgs.o qrc_imgs.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

